### ISSUE TITLE
请问各个插件之间的cookie能否共享？

### ISSUE THREAD

**Issue by gdtv** [jae-jae/QueryList#10]
您好，我在QueryList 3.0的文档里看到说“模拟登录插件和多线程插件的cookie无法共享”，请问在QueryList 4.0里面各个插件之间能否共享cookie？特别是phantomjs插件能否和其他插件共享cookie？

**Comment by jae-jae** [comment]
QueryList4的内置Htpp客户端默认已经开启了cookie共享了，但多线程插件是基于CurlMulti实现的，不是基于内置的Http客户端实现的，所以cookie不是共享的。你可以查看GuzzleHttp文档和CurlMulti文档，自行研究如何让他们共享cookie。
