### ISSUE TITLE
laravel6下采集

### ISSUE THREAD

**Issue by GabbyMrH** [jae-jae/QueryList#107]
在laravel6(php7.3)下采集数据只能取到一条或两条数据，我以为是我配置问题，直到上官网介绍的
[文档示例列表采集](https://querylist.cc/docs/guide/v4/scraper-list)上的「列表采集」案例，复制该案例下来时，发现只能采集到一条数据,官网代码：
`    public function queryList()
    {
        $url = 'https://it.ithome.com/ityejie/';
        // 元数据采集规则
        $rules = [
            'title' => ['h2>a','text'],
            'link' => ['h2>a','href'],
            'img' => ['.list_thumbnail>img','src'],
            'desc' => ['.memo','text']
        ];
        // 切片选择器
        $range = '.ulcl';
        $rt = QueryList::get($url)->rules($rules)->range($range)->query()->getData();

        dd($rt->all());

    }`

**Comment by GabbyMrH** [comment]
对了，QueryList是最新版本的.

**Comment by jae-jae** [comment]
目标网站结构发生了变化，range选择器改成`.content li`就可以了
