### ISSUE TITLE
测试了几个页面,数据采集不全

### ISSUE THREAD

**Issue by linkwss** [jae-jae/QueryList#11]
$html = file_get_contents('http://xxxxx‘’);
        var_dump($html);  // 获取到了全部页面
        //然后可以把页面源码或者HTML片段传给QueryList
        $data = QueryList::html($html)->rules([  //设置采集规则
            // 采集所有a标签的href属性
            'link' => ['.test','href'],
            // 采集所有a标签的文本内容
            'text' => ['.test','text']
        ])->query()->getData();
        //打印结果
        print_r($data->all());  //很多时候只匹配到了前几个，后几个匹配不到

**Comment by jae-jae** [comment]
数据不全一般有3个可能：
1. 选择器问题：没有正确的设置选择器
2. 内容动态加载问题：你在页面上所看到的内容只有部分内容是服务器端渲染出来的，其他内容是动态加载的。
3. HTML中有特殊字符或繁体字：这是phpQuey的bug,遇到这种字符时会导致内容截断，导致内容不全

**Comment by navysummer** [comment]
打印的样式和官方的样式也是不一样
