### ISSUE TITLE
Class 'Tightenco\Collect\Support\Collection' not found

### ISSUE THREAD

**Issue by timelessz** [jae-jae/QueryList#111]

**Comment by timelessz** [comment]
laravel 框架中报错

**Comment by myzingy** [comment]
laravel 5.5.48 中也遇见了

**Comment by AiMovie** [comment]
我也遇到这个问题

**Comment by jiangxianli** [comment]
同问， 无解吗？

**Comment by jae-jae** [comment]
已更新 collect 包

**Comment by mr-chen-king** [comment]
composer安装 4.2.6 这个版本出现这个报错，我当前laravel版本5.5.49
- Conclusion: don't install laravel/framework v5.5.50
    - Conclusion: remove laravel/framework v5.5.49
    - Conclusion: don't install laravel/framework v5.5.49
    - Conclusion: don't install laravel/framework v5.5.48
    - Conclusion: don't install laravel/framework v5.5.47
    - Conclusion: don't install laravel/framework v5.5.46
    - Conclusion: don't install laravel/framework v5.5.45
    - Conclusion: don't install laravel/framework v5.5.44
    - Conclusion: don't install laravel/framework v5.5.43
    - Conclusion: don't install laravel/framework v5.5.42
    - Conclusion: don't install laravel/framework v5.5.41
    - Conclusion: don't install laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.39
    - Conclusion: don't install laravel/framework v5.5.38
    - Conclusion: don't install laravel/framework v5.5.37
    - Conclusion: don't install laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.35
    - Conclusion: don't install laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.33
    - Conclusion: don't install laravel/framework v5.5.32
    - Conclusion: don't install laravel/framework v5.5.31
    - Conclusion: don't install laravel/framework v5.5.30
    - Conclusion: don't install laravel/framework v5.5.29
    - Conclusion: don't install laravel/framework v5.5.28
    - Conclusion: don't install laravel/framework v5.5.27
    - Conclusion: don't install laravel/framework v5.5.26
    - Conclusion: don't install laravel/framework v5.5.25
    - Conclusion: don't install laravel/framework v5.5.24
    - Conclusion: don't install laravel/framework v5.5.23
    - Conclusion: don't install laravel/framework v5.5.22
    - Conclusion: don't install laravel/framework v5.5.21
    - Conclusion: don't install laravel/framework v5.5.20
    - Conclusion: don't install laravel/framework v5.5.19
    - Conclusion: don't install laravel/framework v5.5.18
    - Conclusion: don't install laravel/framework v5.5.17
    - Conclusion: don't install laravel/framework v5.5.16
    - Conclusion: don't install laravel/framework v5.5.15
    - Conclusion: don't install laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.13
    - Conclusion: don't install laravel/framework v5.5.12
    - Conclusion: don't install laravel/framework v5.5.11
    - Conclusion: don't install laravel/framework v5.5.10
    - Conclusion: don't install laravel/framework v5.5.9
    - Conclusion: don't install laravel/framework v5.5.8
    - Conclusion: don't install laravel/framework v5.5.7
    - Conclusion: don't install laravel/framework v5.5.6
    - Conclusion: don't install laravel/framework v5.5.5
    - Conclusion: don't install laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.3
    - Installation request for jaeger/querylist 4.2.6 -> satisfiable by jaeger/querylist[V4.2.6].
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - jaeger/querylist V4.2.6 requires tightenco/collect ^8.0 -> satisfiable by tightenco/collect[v8.0.0, v8.0.4].
    - don't install tightenco/collect v8.0.0|don't install laravel/framework v5.5.0
    - don't install tightenco/collect v8.0.4|don't install laravel/framework v5.5.0
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3
, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.41, v5.5.42, v5.5.43, v5.5.44, v5.5.45, v5.5.46, v5.5.47, v5.5.48, v5.5.49, v5.5.5, v5.5.50, v5.5.6, v5.5.7, v5.5.8, v5.5.9].

**php artisan --version**
Laravel Framework 5.5.49

**Comment by huxiuhang** [comment]
> 已更新 collect 包
laravel5.5安装依然报错，  Class 'Tightenco\Collect\Support\Collection' not found

**Comment by lazyou** [comment]
我也碰到这个问题。啥情况。

**Comment by dingxiangjun** [comment]
我也碰到这个问题了

**Comment by aze963622** [comment]
一样的问题  laravel5.5

**Comment by 2723659854** [comment]
怎么解决这个问题额，安装哪一个版本都不对
