### ISSUE TITLE
querylist如何获取到当前请求的cookies和headers?

### ISSUE THREAD

**Issue by akrick** [jae-jae/QueryList#117]
querylist如何获取到当前请求的cookies和headers?

**Comment by akrick** [comment]
use QL\QueryList;
use GuzzleHttp\Cookie\CookieJar;

$jar = new CookieJar();

$ql = QueryList::post('http://xxx.com/login', [
    'username' => 'admin',
    'password' => 'admin',
],[
    'cookies' => $jar
]);
2.第二步：保存 cookie 到本地

$cookieArr = $jar->toArray();
file_put_contents('./xx_cookie.txt', json_encode($cookieArr));

**Comment by amhoho** [comment]
@akrick 按照二楼这个方法,登陆后得到的却是空的cookie,这个时候的$jar确定是post之后生成的cookie吗?
