### ISSUE TITLE
关于使用CURL多线程插件的问题

### ISSUE THREAD

**Issue by duckjiangwei** [jae-jae/QueryList#118]
只要传入的url数组中有一个地址是无效的,比如说有个url是'saasdasdsdfs',就会导致整个抓取报错

**Comment by jenzh** [comment]
有个语法叫try ... catch

**Comment by amd5** [comment]
> 有个语法叫try ... catch

只能捕获全部(整个多线程请求逻辑),无法捕获单个线程url请求错误,

**Comment by duckjiangwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
