### ISSUE TITLE
错误报告Document with ID '67ca6e7b6472494a20aff43a4739ab59' isn't loaded. Use phpQuery::newDocument($html) or phpQuery::newDocumentFile($file) first.

### ISSUE THREAD

**Issue by windpursuer** [jae-jae/QueryList#12]
挂机采集时出现错误报告Document with ID '67ca6e7b6472494a20aff43a4739ab59' isn't loaded. Use phpQuery::newDocument($html) or phpQuery::newDocumentFile($file) first.请问是什么原因造成的？

**Comment by windpursuer** [comment]
隔20秒左右就会出现一次，每次ID不同

**Comment by windpursuer** [comment]
有人可以解疑吗？

**Comment by mountainguan** [comment]
我也遇到一样的情况，不知道问题是什么产生的，每次执行完都销毁了

**Comment by jae-jae** [comment]
我需要一份能重现这个错误的代码来做分析，可以加QueryList交流群，然后私发给我

**Comment by mountainguan** [comment]
我知道怎么解决了，应该是因为循环调用静态的QueryList，但是每次调用的静态get方法都会创建新的phpQuery对象，导致积压在内存中，内存爆了，就存不了新爬到的内容。
（destruct方法不能回收对象资源，只能去掉不必要的旧html缓存，这个问题应该需要解决一下，毕竟querylist全都是静态方法，会常驻内存，但是每次调用的phpQuery却又是重新创建一个。）
解决方法，只初始化一个`$ql = QueryList::getInstance();` ，后面就一直用这个对象，刚刚爬了几百个页面都没事，之前爬50个页面就爆了。 @jae-jae @windpursuer

**Comment by jae-jae** [comment]
你这才是正确用法，看看QueryList官方文档给出的例子:
![](https://ws3.sinaimg.cn/large/7de3675bgy1fmh8yt8pkgj21am0ezdj9.jpg)

**Comment by mountainguan** [comment]
@jae-jae 或许把这个报错列出来提示新手遇到怎么解决会比较好，因为刚开始用也是糊里糊涂

**Comment by jae-jae** [comment]
我做一个专题

**Comment by windpursuer** [comment]
@mountainguan 感谢，就是你说的那种情况，我从数据库里取出待爬url列表后就不停循环创建新对象来抓取详情页，然后就爆掉了。@jae-jae 辛苦大神

**Comment by ooking** [comment]
还有一个注意的是
$ql = QueryList::getInstance(); 
之后
记得不要用静态方法来调用例如：$ql::html($html) 否则内存爆了还是会出错
都得改成 $ql->html($html)

**Comment by smz-web** [comment]
没有办法解决

**Comment by smz-web** [comment]
手册上的根本没用

**Comment by KouSum** [comment]
rules 不是rule
