### ISSUE TITLE
当gethtml方法返回json时，json中的字符串如果存在双引号，会破坏json的格式， 如：&quot;

### ISSUE THREAD

**Issue by susiwang35** [jae-jae/QueryList#120]
当gethtml方法返回json时，json中的字符串如果存在双引号，会破坏json的格式， 如：&quot;
`[{"ask":1,"message":"","data":{"order_id":"176405","data_source":"walmart","platform":"walmart","warehouse_id":"1","user_account":"walmart","order_status":"4","country_code":"CA","sys_tips":"","abnormal_type":"0","process_again":"1","ShippingAddress_Id":"176444","Company_name":"","Name":"Renee Boudreau","Instructions":null,"Street1":"98 Alabaster Way","Street2":"","Street3":"","District":"","Country":"CA[\u52a0\u62ff\u5927]","CityName":"HALIFAX","StateOrProvince":"NS","County":null,"CountryName":"CA","Phone":"9025789578","PostalCode":"B3P 0E6","AddressID":"","AddressOwner":"","ExternalAddressID":"","OrderID":"WAL-0079-Y16608728","Plat_code":"walmart","company_code":"jyj","create_date_sys":"2020-05-02 09:33:03","modify_date_sys":"2020-05-02 09:33:03","is_modify":"0","doorplate":null,"address_type":"","original_address_type":"","shopify_address_type":"","phone_area":null,"ec_update_time":"2020-05-02 09:33:03","ec_create_time":"2020-05-02 09:33:03","refrence_no_platform":"WAL-0079-Y16608728","refrence_no_warehouse":"WAL20050270006","refrence_no":"Y16608728","date_earliest_ship":null,"date_latest_ship":"2020-05-06 14:00:00","product_count":"1","subtotal":"349.990","refrence_no_sys":"6882039001700","order_type":"sale","has_buyer_note":"0","order_refund":null,"refund_val":"","order_product":[{"op_id":"211653","order_id":"176405","product_id":"0","product_sku":"HMUS-020012MB-10IN","warehouse_sku":"HMUS-020012MB-10IN*1*100.000","product_title":"Homary Ultra Thin 10" Rain Showerhead Dual Function Wall Mounted Shower Sys","op_quantity":"1","stock_quantity":"0","op_ref_tnx":"","op_recv_account":"","op_ref_item_id":"1","op_ref_item_location":"","op_site":"","op_record_id":"","op_ref_buyer_id":"","op_ref_paydate":"0000-00-00 00:00:00","op_add_time":"2020-05-02 09:33:03","op_update_time":"2020-05-02 09:33:03","OrderID":"WAL-0079-Y16608728","OrderIDEbay":"Y16608728","is_modify":"0","pic":"","url":"","unit_price":"349.990","transaction_price":"349.990","unit_finalvaluefee":"52.498","unit_platformfee":"0.000","unit_shipfee":"0.000","unit_fba_fee":"0.000","unit_other_fee":"0.000","currency_code":"CAD","sync_status":"0","give_up":"0","create_type":"api","fba_fee":"","price_designation":null,"send_goods_operator_type":"0","properties":"","is_customized":"-1","declare_name_cn":"","declare_name_en":"","logistics_warehouse_type":"0","ec_update_time":"2020-05-02 09:33:03","ec_create_time":"2020-05-02 09:33:03","is_gift":"0","is_hba_up_express":"0","is_lead_time_tag":"0","lead_time_tag_days":"0","sub_product":[{"op_quantity":"1","product_sku":"HMUS-020012MB-10IN","asin1":"","detail_page":"","pcr_product_sku":"HMUS-020012MB-10IN","pcr_product_img":"http:\/\/jyj.eccang.com\/swfupload\/upload\/201810\/31\/1540966141_gZ1LH_100x100.jpg","product_title":"HMUS-020012\u54d1\u9ed1-10\u5bf8","product_title_en":"HMUS-020012MB-10IN","pcr_quantity":1,"pcr_percent":"100.000","product_id":"7373","product_barcode":"HMUS-020012MB-10IN","message":"","sale_status":"\u5728\u7ebf\u4ea7\u54c1"}],"warehouse_sku_title":"HMUS-020012\u54d1\u9ed1-10\u5bf8"}],"shipstation_list_store":null}}]
`
因为这个JSON中的title 里有双引号&quot;被转义，导致多了双引号，致使JSON格式错误

**Comment by jae-jae** [comment]
如果是抓取JSON数据的话，建议直接使用 Guzzle HTTP Client
