### ISSUE TITLE
Add support Laravel ^8.0 and guzzle ^7.0.1

### ISSUE THREAD

**Issue by mishabachkur** [jae-jae/QueryList#122]

**Comment by chuihai** [comment]
Your requirements could not be resolved to an installable set of packages.
 
   Problem 1
     - Installation request for jaeger/querylist ^4.2.5 -> satisfiable by jaeger/querylist[V4.2.5].
     - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
     - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
     - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
     - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
     - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
     - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].
 
 Failed to update packages for  ./composer.json.

**Comment by jae-jae** [comment]
done
