### ISSUE TITLE
请支持 guzzle 7.0.1！原因6x版本有很多网页404

### ISSUE THREAD

**Issue by chuihai** [jae-jae/QueryList#123]
例如‘http://www.886mh.com/fenji/743861.html ’
如果使用 guzzle6x版本 也就是现在的  QueryList 4.2 版本 ，获取不到！ 这个应该guzzle 版本问题 ？ 冒昧的问一下官网的测试 QueryList 是那个版本？ 测试版本 可以获取到内容！

**Comment by jae-jae** [comment]
已升级

**Comment by chuihai** [comment]
非常感谢你
