### ISSUE TITLE
吐槽一下

### ISSUE THREAD

**Issue by hunteryun** [jae-jae/QueryList#125]
二千的星，居然还没人家隔壁的https://packagist.org/packages/laolei/stole的一击就成功好用，你家这货，一上来就报错，什么Tag header invalid in Entity,  还死活全网查不到相关任何信息，你是不是该反思一下？

**Comment by chuoke** [comment]
大量语法错误

**Comment by jae-jae** [comment]
> 二千的星，居然还没人家隔壁的[https://packagist.org/packages/laolei/stole的一击就成功好用，你家这货，一上来就报错，什么Tag](https://packagist.org/packages/laolei/stole%E7%9A%84%E4%B8%80%E5%87%BB%E5%B0%B1%E6%88%90%E5%8A%9F%E5%A5%BD%E7%94%A8%EF%BC%8C%E4%BD%A0%E5%AE%B6%E8%BF%99%E8%B4%A7%EF%BC%8C%E4%B8%80%E4%B8%8A%E6%9D%A5%E5%B0%B1%E6%8A%A5%E9%94%99%EF%BC%8C%E4%BB%80%E4%B9%88Tag) header invalid in Entity, 还死活全网查不到相关任何信息，你是不是该反思一下？

![FAQ](https://user-images.githubusercontent.com/5620429/97996462-c2272a00-1e22-11eb-83e5-2428b5f58ce6.png)
这类错误的原因是PHP的 `DOMDocument` 类 `loadHTML` 方法在解析不规范的HTML页面源码的时候产生的警告信息, 通过 `libxml_use_internal_errors(true);` 语句即可屏蔽这类警告信息，QueryList 的 FAQ 章节有说明，并且复制错误信息到 Google 就可以搜出一大堆相关错误相关问题以及解决方案。

**Comment by jae-jae** [comment]
> 大量语法错误

可以具体描述一下遇到什么错误

**Comment by srcker** [comment]
我真的不想吐槽 最新版本要PHP7.2支持啊 不是7.1 
项目跑步起来找了半天原因 我们是php7.1.7 
最新要7.2支持 我擦 找了半天原因 没想到是这个包

**Comment by lomsing** [comment]
用官网生成的采集规则代码是正常的，放到我自己代码最终执行结果不一致？？笑死我

**Comment by guokeu** [comment]
QueryList-4.2.7\vendor\jaeger\phpquery-single\phpQuery.php:462行
```
	protected function contentTypeFromHTML($markup) {
		$matches = array();
		// find meta tag
		preg_match('@<meta[^>]+http-equiv\\s*=\\s*(["|\']*)Content-Type\\1([^>]*)>@i',// 这里有bug
```

**Comment by guokeu** [comment]
> QueryList-4.2.7\vendor\jaeger\phpquery-single\phpQuery.php:462行
> 
> ```
> 	protected function contentTypeFromHTML($markup) {
> 		$matches = array();
> 		// find meta tag
> 		preg_match('@<meta[^>]+http-equiv\\s*=\\s*(["|\']*)Content-Type\\1([^>]*)>@i',// 这里有bug
> ```

这里导致get GB2312页面乱码，即便修复了这里也有别的问题。
