### ISSUE TITLE
遇到ajax加vue的采集失败

### ISSUE THREAD

**Issue by Nakasu-ksm** [jae-jae/QueryList#126]
遇到ajax加vue的采集失败，页面数据动态渲染，显示{{xxx.xxx}}为没渲染之前的，因为ajax进行了加密并且js也进行了加密所以无法采集啊

**Comment by jae-jae** [comment]
JS动态渲染的页面，需要使用 Puppeteer  插件：http://querylist.cc/docs/guide/v4/Puppeteer
