### ISSUE TITLE
 each() 函数已在 php 7.2 以上版本被移除，是否可以兼容一下高版本的 php 语言呢~

### ISSUE THREAD

**Issue by zhaoqinghuan** [jae-jae/QueryList#129]
如题所示。
![image](https://user-images.githubusercontent.com/28949050/102453461-34706880-4077-11eb-8e6a-c47dd47747bb.png)
![image](https://user-images.githubusercontent.com/28949050/102453526-54a02780-4077-11eb-8dce-8bd5a98f2c80.png)

**Comment by jae-jae** [comment]
你使用的是 QueryList 那个版本?

**Comment by zhaoqinghuan** [comment]
![image](https://user-images.githubusercontent.com/28949050/102571682-06e1f880-4125-11eb-9951-2086c2908bf8.png)
`3.2.1`

**Comment by zhaoqinghuan** [comment]
> 你使用的是 QueryList 那个版本?
![image](https://user-images.githubusercontent.com/28949050/102571718-2bd66b80-4125-11eb-9288-da8ad08cb701.png)
`3.2.1`

**Comment by jae-jae** [comment]
QueryList 3 版本已经不再维护了，目前的解决方法只能是你自己 fork 一份代码，然后去维护了

**Comment by geelinsir** [comment]
可以考虑重写each函数：
function each(&$array){
   $res = array();
   $key = key($array);
   if($key !== null){
       next($array); 
       $res[1] = $res['value'] = $array[$key];
       $res[0] = $res['key'] = $key;
   }else{
       $res = false;
   }
   return $res;
}
