### ISSUE TITLE
laravel5.5 出现 Class 'Tightenco\Collect\Support\Collection' not found

### ISSUE THREAD

**Issue by lazyou** [jae-jae/QueryList#131]
laravel5.5 出现 Class 'Tightenco\Collect\Support\Collection' not found
QueryList V4.2.7， 也没法退回到V4.2.6，有冲突

**Comment by dingxiangjun** [comment]
我也遇到这个问题了

**Comment by jae-jae** [comment]
Upgrade to V4.4.3
