### ISSUE TITLE
QueryList::html和QueryList::get有什么不同?有点不懂

### ISSUE THREAD

**Issue by zzos** [jae-jae/QueryList#134]
QueryList::get采集了QueryList::html采集不到的数据，但有个疑问。
一个页面多条采集规则是用     QueryList::html   还是   QueryList::get
我理解为    QueryList::html  get 一次 储存  多条规则匹配无需再 get
                  QueryList::get  每匹配一次采集规则都需要get 一次

**Comment by jae-jae** [comment]
QueryList::get 等价于 curl + QueryList::html , 关于复用采集的技巧可以参考这篇教程最后几个例子：http://querylist.cc/docs/guide/v4/scraper-list
