### ISSUE TITLE
querylistV3版本怎么安装Request扩展？

### ISSUE THREAD

**Issue by klmahua** [jae-jae/QueryList#135]
看文档的安装命令  composer require jaeger/querylist-ext-request  怎么安装不上报错
另外附加querylistV3安装命令：composer require jaeger/querylist:V3.2.1   
请大佬解惑！！！！

**Comment by jae-jae** [comment]
具体报什么错？

**Comment by klmahua** [comment]
已经安装成功了。。。原来是连接不上镜像，，改成阿里云镜像就好了。。。。另外求教管理  v3版本  IP代理模式什么写法？？v3文档中没找到相关说明例子。。。。感谢

**Comment by jae-jae** [comment]
这个库有些旧了，不支持IP代理，建议使用　GuzzleHttp　这个包。

**Comment by klmahua** [comment]
> 
> 
> 这个库有些旧了，不支持IP代理，建议使用　GuzzleHttp　这个包。
没办法项目不支持php7，只能使用v3版本，，，，，用过GuzzleHttp这个包，采集58内容总是空白，，，不好用，，，querylist去掉头部后可以采集到内容
