### ISSUE TITLE
怎么通过queryList获取返回头信息

### ISSUE THREAD

**Issue by hkui** [jae-jae/QueryList#136]
比如获取是不是200,302之类的一些头信息
能通过QueryList来获取吗

还是只能这样吗
```php
$client = GHttp::getClient();
$args=[];
$response = $client->request('GET', $url,$args);
$header=$response->getHeader('set-cookie');
```

**Comment by jae-jae** [comment]
![image](https://user-images.githubusercontent.com/5620429/112780018-882d1d80-907a-11eb-8b3a-2c1eefeb8d2f.png)
文档中有说明
