### ISSUE TITLE
Composer安装的库和说明文档不一样？

### ISSUE THREAD

**Issue by a2htray** [jae-jae/QueryList#14]

**Comment by jae-jae** [comment]
问题可以再描述具体一点吗？

**Comment by willmao8** [comment]
文档里有 QueryList::get() 我看 composer安装的 并没有get方法

**Comment by willmao8** [comment]
我看懂了 git上的文档有问题 你那边链接提供的API 里头没问题 我说呢 看代码 就一个query方法
