### ISSUE TITLE
使用multiGet并发请求时怎么获取所有请求全部完成

### ISSUE THREAD

**Issue by cqsn558** [jae-jae/QueryList#144]
我在采集内容页时使用multiGet并发获取采集数据，因为在所有url内容采集完毕时还要程序执行其他操作，看了multiGet的示例和文档，success()是每个线程成功后的回调，有什么办法可以在所有线程完毕后执行其他操作？

**Comment by jae-jae** [comment]
multiGet执行 `send()` 方法后会堵塞直到所有请求完成，之后会继续执行后面代码逻辑
