### ISSUE TITLE
可以加载html 但是find找不到内容

### ISSUE THREAD

**Issue by AdolphYu** [jae-jae/QueryList#146]
[content.txt](https://github.com/jae-jae/QueryList/files/6860860/content.txt)

$q = QueryList::html($content);
$a = $q->find('h1 span')->text();

输出为空字符串

**Comment by jae-jae** [comment]
可能是QueryList解析内容失败，可以通过 `getHtml()` 方法测试，打印 QueryList 解析的内容：
```
$ql = QueryList::html($html);
$html = $ql->getHtml(true);
echo $html;
```
相关文档：https://querylist.cc/docs/api/v4/getHtml
