### ISSUE TITLE
请问一下PHP8的支持计划！！

### ISSUE THREAD

**Issue by alawnchen** [jae-jae/QueryList#147]
如题，请问一下什么时候可以支持PHP8。

**Comment by jae-jae** [comment]
一直都支持 PHP8

**Comment by alawnchen** [comment]
<img width="869" alt="截屏2021-08-08 上午1 14 59" src="https://user-images.githubusercontent.com/1811463/128608548-9e0bdc57-fc58-41bf-befc-4dd28b37713a.png">
是真的不行的，是jaeger/g-http依赖的cache/filesystem-adapter要求php5.6或者php7.0。

**Comment by alawnchen** [comment]
我查了一下cache/filesystem-adapter1.1.0已经支持php8。jaeger/g-http现在依赖的是cache/filesystem-adapter1.0。麻烦更新一下可以吗？
<img width="530" alt="截屏2021-08-08 上午1 22 18" src="https://user-images.githubusercontent.com/1811463/128608747-20e195ea-ea64-450b-a1e5-0883da8ce17e.png">

**Comment by jae-jae** [comment]
已更新

**Comment by edresqaderi** [comment]
it did not resolve
