### ISSUE TITLE
4.2.8 版本 没法用啊

### ISSUE THREAD

**Issue by cokyhe** [jae-jae/QueryList#151]
composer 升级到新版4.2.8后，
QueryList::get($cai_url)->rules([ 
	    'title'=>array('h3','text'),
	    'link'=>array('h3>a','href')
	])->query()->getData();
只能得到：Array
        (
            [title] => Angular - QueryList
            [link] => https://angular.io/api/core/QueryList
        )

没法得到多维数组了，回退到之前使用的4.0.1 就正常了

**Comment by Fucntion** [comment]
me too

**Comment by jae-jae** [comment]
没有设置 `range()` 的原因

**Comment by 8108905** [comment]
建议看下文档
