### ISSUE TITLE
设置的代理需要验证账号密码如何填写？

### ISSUE THREAD

**Issue by xinyusuifengsb** [jae-jae/QueryList#154]
// 设置代理
    'proxy' => 'http://222.141.11.17:8118',
    //设置超时时间，单位：秒
    'timeout' => 30,

例如上面的proxy 222.141.11.17:8118 使用时需要验证账号密码，这个如何填写？

**Comment by jae-jae** [comment]
guzzlehttp proxy auth:
```
"proxy" => "http://username:password@192.168.16.1:10",
```
