### ISSUE TITLE
发现当匹配不到的时候，就会删除该采集内容，回调函数无用？

### ISSUE THREAD

**Issue by indiboy** [jae-jae/QueryList#16]
能出采集不到也可以用回调函数给一个默认值？

**Comment by jae-jae** [comment]
可以在`getData() `方法回调函数中处理这件事情，具体做法查看`getData()`方法文档。

**Comment by bvcvb** [comment]
这不对,如果a的length 为10, a[2]里的某个属性m采集不到 却用a[3]的m来顶上 整个结果是错误的 到了getData里的回调函数已经错乱了....

**Comment by jae-jae** [comment]
文档里有队这种现象的解释：https://doc.querylist.cc/site/index/doc/14

**Comment by bvcvb** [comment]
教训呃,文档没看全,多谢jae....
