### ISSUE TITLE
Add support laravel 9

### ISSUE THREAD

**Issue by mishabachkur** [jae-jae/QueryList#161]

**Comment by xtrime-ru** [comment]
Add this alias to your composer.json: 

```shell
 composer require "league/flysystem:3.1 as 1.99"
```

Probably filecache in g-http will be broken, but other stuff works.

**Comment by mishabachkur** [comment]
> Add this alias to your composer.json:
> 
> ```shell
>  composer require "league/flysystem:3.1 as 1.99"
> ```
> 
> Probably filecache in g-http will be broken, but other stuff works.

@xtrime-ru This solution is not working

**Comment by xtrime-ru** [comment]
@mishabachkur What exactly is the issue?

Im using this fix in one of my projects: https://github.com/xtrime-ru/ICA/blob/dev/composer.json#L24

**Comment by mishabachkur** [comment]
@xtrime-ru It was my inattention. Thanks for the solution

**Comment by jae-jae** [comment]
Upgrade to V4.4.3
