### ISSUE TITLE
期望实现devtools-protocol，就能和puppeteer一样愉快的使用了

### ISSUE THREAD

**Issue by jingjingxyk** [jae-jae/QueryList#166]
缘由：想和puppeteer 一样愉快的使用：[chrome-remote-interface](https://github-com.proxy.dengxiaci.com/cyrus-and/chrome-remote-interface)

参考文档：
1. https://chromedevtools.github.io/devtools-protocol/
2. https://github.com/ChromeDevTools/awesome-chrome-devtools.git

**Comment by jae-jae** [comment]
可参考插件开发文档自行实现：https://querylist.cc/v4/guide/extension-development.html ，很简单
