### ISSUE TITLE
 PHP7.4环境代码执行结果与预期不一致！

### ISSUE THREAD

**Issue by loveyxh** [jae-jae/QueryList#168]
【运行环境】
PHP 7.4.33 

【执行代码】
$data = QueryList::get('http://www.baidu.com/s?wd=QueryList')
	// 设置采集规则
    ->rules([ 
	    'title'=>array('h3','text'),
	    'link'=>array('h3>a','href')
	])
	->query()->getData();

print_r($data->all());

【实际执行结果】
Array
(
    [title] => QueryList|优雅的渐进式PHPDOM解析框架快速上手 - QueryList文档QueryList - 简洁、优雅的 PHP 采集工具(爬虫)PHP爬虫框架 Querylist_腾讯新闻抓取网页工具querylist的使用简介 - 简书简单的使用QueryList爬取数据_弟弟小王的博客-CSDN博客PHP框架 | QueryList优雅的渐进式PHP采集框架-百知教育IT...QueryList入门_学不会就继续学的博客-CSDN博客GitHub - jae-jae/QueryList: The progressive PHP crawle...Python querylist_专题 - Python中文网
    [link] => http://www.baidu.com/link?url=wLcfBNj5P44mIoe7-D6caynW6Vd7lC3ImmIEfvNJ7HKG_YZsvBVb_RJoP7ypX0zz
)

执行预期是一个二维数组，结果确实一个一维数组
所有标题，都合并到title字段了

【预期结果】
Array
(
    [0] => Array
        (
            [title] => QueryList|基于phpQuery的无比强大的PHP采集工具
            [link] => http://www.baidu.com/link?url=GU_YbDT2IHk4ns1tjG2I8_vjmH0SCJEAPuuZN
        )
    [1] => Array
        (
            [title] => PHP 用QueryList抓取网页内容 - wb145230 - 博客园
            [link] => http://www.baidu.com/link?url=zn0DXBnrvIF2ibRVW34KcRVFG1_bCdZvqvwIhUqiXaS
        )
    [2] => Array
        (
            [title] => 介绍- QueryList指导文档
            [link] => http://www.baidu.com/link?url=pSypvMovqS4v2sWeQo5fDBJ4EoYhXYi0Lxx
        )
        //...
)

**Comment by wqjohnston** [comment]
解决了吗

**Comment by wqjohnston** [comment]
解决了吗  我用着也是这样

**Comment by SQSora** [comment]
我也遇到了相同的情况 PHP7.3

**Comment by jae-jae** [comment]
采集列表需要制定 range() 参数，参考教程：https://querylist.cc/v4/guide/scraper-list.html
