### ISSUE TITLE
QueryList4.2.8列表采集，不能正常执行

### ISSUE THREAD

**Issue by jenawant** [jae-jae/QueryList#174]
代码如下：
`$url  = $_GET['url'] ?? "https://ishere.cn/";
$data = QueryList::get($url)->encoding('UTF8')->rules(
    [
        'title' => ['a', 'text'],
        'link'  => ['a', 'href']
    ]
)->query()->getData();`

执行结果如下：
`{
    "title": "首页与我取得联系在之前。。忽略中间所有文字。。。rtPanel WordPress Theme Framework鲁ICP备14011120号",
    "link": "http:\/\/ishere.cn\/"
}`

请指教，谢谢

**Comment by jae-jae** [comment]
采集列表需要制定 range() 参数，参考教程：https://querylist.cc/v4/guide/scraper-list.html
