### ISSUE TITLE
thinkphp8框架

### ISSUE THREAD

**Issue by xiaoloner** [jae-jae/QueryList#177]
thinkphp8框架能否支持使用QueryList?

**Comment by jae-jae** [comment]
thinkphp8 安装 QueryList v4.2.9 版本，目前是存在什么问题，依赖冲突吗？

**Comment by xiaoloner** [comment]
thinkphp8单独安装没问题，与其他后台搭配使用就会有依赖冲突，比如说funadmin、uiadmin

**Comment by jae-jae** [comment]
具体是哪个依赖存在冲突？可以贴上依赖冲突的错误日志我看一下

**Comment by xiaoloner** [comment]
![20240421154020](https://github.com/jae-jae/QueryList/assets/14234979/5fed13d8-34bc-4f01-9dc1-cebe3df53a15)

**Comment by pyj2004** [comment]
![image](https://github.com/jae-jae/QueryList/assets/8112267/e4da3f29-e8b1-4e9a-8d5c-fff35643f033)
一样的出现这个问题

**Comment by jae-jae** [comment]
已修复，安装 V4.4.3 版本
