### ISSUE TITLE
难道你们都没有这个致命错误？

### ISSUE THREAD

**Issue by 895268679long** [jae-jae/QueryList#178]
$groupKey = match (true) {
                    is_bool($groupKey) => (int) $groupKey,
                    $groupKey instanceof \Stringable => (string) $groupKey,
                    default => $groupKey,
                };
错误是语法解析错误: syntax error, unexpected '=>' (T_DOUBLE_ARROW)

我用的是fastadmin

**Comment by jae-jae** [comment]
match 是 PHP 8.1 引入的新特性，确认一下你的 PHP 版本，另外报错的这段代码并不是 QueryList 的代码

**Comment by 37521484** [comment]
可是大哥 你官网写的php要求是7.1啊   现在php7安装了  这个版本又有php8的代码

**Comment by jae-jae** [comment]
我都说了报错的这段代码并不是 QueryList 的代码，你检查一下报错文件是哪一个？定位一下是哪个包导致的报错

**Comment by 895268679long** [comment]
> 我说了报错的可能代码不是 QueryList 的代码，你检查一下报错文件是哪一个？定位一下是哪个包导致的报错

不是很清楚。又出现了奇怪的错误
[ error ] [64]Declaration of QL\Collect\Support\Collection::jsonSerialize(): array must be compatible with QL\Collect\Support\Enumerable::jsonSerialize(): QL\Collect\Support\mixed[/vendor/jaeger/querylist/src/Collect/Support/Collection.php:855]

另外我php版本是7.4 我很想用，但是安装总是有问题。 另外安装后又出现了奇怪的问题。 我的脚本原来正常运行， 昨天装了插件后报错了一夜。fack  错误内容是Array to string conversion。 我并没有找到具体是哪里。 赶紧卸载了插件

**Comment by ymiras** [comment]
> > 我说了报错的可能代码不是 QueryList 的代码，你检查一下报错文件是哪一个？定位一下是哪个包导致的报错
> 
> 不是很清楚。又出现了奇怪的错误 [ error ] [64]Declaration of QL\Collect\Support\Collection::jsonSerialize(): array must be compatible with QL\Collect\Support\Enumerable::jsonSerialize(): QL\Collect\Support\mixed[/vendor/jaeger/querylist/src/Collect/Support/Collection.php:855]

4.2.8 能正常运行。

**Comment by 895268679long** [comment]
> > > 我说了报错的可能代码不是 QueryList 的代码，你检查一下报错文件是哪一个？定位一下是哪个包导致的报错
> > 
> > 
> > 不是很清楚。又出现了奇怪的错误 [ error ] [64]Declaration of QL\Collect\Support\Collection::jsonSerialize(): array must be compatible with QL\Collect\Support\Enumerable::jsonSerialize(): QL\Collect\Support\mixed[/vendor/jaeger/querylist/src/Collect/Support/Collection.php:855]
> 
> 4.2.8 能正常运行。

谢谢。我试了 这个版本似乎是正常的，终于可与用了
