### ISSUE TITLE
为什么经常有这种错误

### ISSUE THREAD

**Issue by 895268679long** [jae-jae/QueryList#180]
[ error ] [2]DOMDocument::loadHTML(): Unexpected end tag : meta in Entity, line: 10[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 30[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag defs invalid in Entity, line: 31[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag path invalid in Entity, line: 32[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag path invalid in Entity, line: 33[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag header invalid in Entity, line: 38[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag main invalid in Entity, line: 107[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag section invalid in Entity, line: 108[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 122[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag circle invalid in Entity, line: 122[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]
[ error ] [2]DOMDocument::loadHTML(): Tag section invalid in Entity, line: 128[/www/wwwroot/xxxxxxxxxxxxx/vendor/jaeger/phpquery-single/phpQuery.php:341]

**Comment by 895268679long** [comment]
我是php7.4 安装的是4.2.8版本

**Comment by jae-jae** [comment]
HTML 结构不规范导致解析出错
