### ISSUE TITLE
版本依赖有问题

### ISSUE THREAD

**Issue by nick2550123097** [jae-jae/QueryList#181]
在hyperf3.1的版本中，安装一直报冲突

➜  server ../devtools/swoole-cli ../devtools/composer.phar require jaeger/querylist=V4.4.3
./composer.json has been updated
Running composer update jaeger/querylist
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jaeger/querylist V4.4.3 -> satisfiable by jaeger/querylist[V4.4.3].
    - jaeger/querylist V4.4.3 requires jaeger/phpquery-single ^1 -> found jaeger/phpquery-single[1.0.0, 1.0.1, 1.1.0, 1.1.1] but the package is fixed to 0.9.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by jae-jae** [comment]
已经给出提示了，使用 --with-all-dependencies  选项允许去升级依赖

**Comment by nick2550123097** [comment]
不行的，应该是两个版本锁定了不兼容，最新版本的larave装这个装不上

**Comment by nick2550123097** [comment]
![abc](https://github.com/jae-jae/QueryList/assets/27957803/003d5307-4045-4afd-8560-75d52aa5c5a6)
能下载但是是空的

**Comment by jae-jae** [comment]
PHP 版本需要 >= 8.1 , 然后安装 V4.4.4 版本，低版本会存在依赖冲突问题

**Comment by nick2550123097** [comment]
Call to undefined function QL\Dom\value()
[ERROR] Error: Call to undefined function QL\Dom\value() in /code/api/server/vendor/jaeger/querylist/src/Dom/Query.php:53
Stack trace:
#0 /code/api/server/vendor/jaeger/querylist/src/QueryList.php(65): QL\Dom\Query->setHtml('<!doctype html>...')
#1 /code/api/server/vendor/jaeger/querylist/src/Services/HttpService.php(34): QL\QueryList->__call('setHtml', Array)
#2 /code/api/server/vendor/jaeger/querylist/src/Providers/HttpServiceProvider.php(21): QL\Services\HttpService::get(Object(QL\QueryList), 'https://www.swo...')
#3 [internal function]: QL\QueryList->QL\Providers\{closure}('https://www.swo...')
#4 /code/api/server/vendor/jaeger/querylist/src/QueryList.php(67): Closure->call(Object(QL\QueryList), 'https://www.swo...')
#5 /code/api/server/vendor/jaeger/querylist/src/QueryList.php(75): QL\QueryList->__call('get', Array)
#6 /code/api/components/api/src/Command/GenUserToken.php(24): QL\QueryList::__callStatic('get', Array)
#7 /code/api/server/vendor/hyperf/command/src/Command.php(177): Cms\Api\Command\GenUserToken->handle()
#8 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()

**Comment by jae-jae** [comment]
已修复，安装 V4.4.5 版本
