### ISSUE TITLE
识别不到函数

### ISSUE THREAD

**Issue by nick2550123097** [jae-jae/QueryList#183]
hyperf安装了 v4.4.4 的时候可以安装，然后 调用报错了

[ERROR] Error: Call to undefined function QL\Dom\value() in /Users/test/hyperf-skeleton/vendor/jaeger/querylist/src/Dom/Query.php:53

**Comment by nick2550123097** [comment]
![abc](https://github.com/jae-jae/QueryList/assets/27957803/e5febb2d-8ea5-4a76-9c76-b92c9601ff13)

**Comment by glitter1105** [comment]
> hyperf安装了 v4.4.4 的时候可以安装，然后 调用报错了
> 
> [ERROR] Error: Call to undefined function QL\Dom\value() in /Users/test/hyperf-skeleton/vendor/jaeger/querylist/src/Dom/Query.php:53

改用4.2.8版本 我试过了 可以

**Comment by jae-jae** [comment]
已修复，安装 V4.4.5 版本
