### ISSUE TITLE
#bug 未定义 value() 函数

### ISSUE THREAD

**Issue by apibrain** [jae-jae/QueryList#184]
在升级了 v4.4 之后，抛出了 Call to undefined function QL\Dom\value() 错误。

文件名：/jaeger/querylist/src/Dom/Query.php
位置：第53行

**Comment by jae-jae** [comment]
升级到 [V4.4.4](https://github.com/jae-jae/QueryList/releases/tag/V4.4.4)

**Comment by l1n6yun** [comment]
jaeger/querylist[V4.4.4, ..., V4.4.6] require php >=8.1
