### ISSUE TITLE
建议加入http ip伪装功能

### ISSUE THREAD

**Issue by mountainguan** [jae-jae/QueryList#20]
加入一个函数，允许把ip传入进行伪装，这样的功能应该配合post，get方法很实用
```
'X-Forwarded-For' => $ip,
'Proxy-Client-IP' => $ip,
'WL-Proxy-Client-IP' => $ip,
'HTTP_CLIENT_IP' => $ip,
'X-Real-IP' => $ip,
```

**Comment by jae-jae** [comment]
建议封装为QueryList插件，然后提交到QueryList插件仓库：[https://github.com/jae-jae/QueryList-Community](https://github.com/jae-jae/QueryList-Community)

**Comment by mountainguan** [comment]
@jae-jae 插件做好了 https://github.com/mountainguan/QLPlugin-DisguisePlugin
