### ISSUE TITLE
使用phantomjs时，请问怎么传递登录后cookie进去

### ISSUE THREAD

**Issue by moyu2008** [jae-jae/QueryList#31]
不使用phantomjs时，看手册会传cookie,但是使用phantomjs时就不知道怎么传入cookie了

**Comment by jae-jae** [comment]
> browser($url,$debug = false,$commandOpt = []):使用浏览器打开连接 ,return QueryList

$commandOpt : 设置phantomjs命令行参数，详情:http://phantomjs.org/api/command-line.html
```
--cookies-file=/path/to/cookies.txt specifies the file name to store the persistent Cookies.
```
