### ISSUE TITLE
php 7.2.3 下ERROR

### ISSUE THREAD

**Issue by kency** [jae-jae/QueryList#32]
composer之后，在laravel里,直接用文档示例
use ....
.....
  $ql = QueryList::get.....
报错"Parse error: syntax error, unexpected '$ql' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)"

php 7.2.3 开发模式

**Comment by jae-jae** [comment]
看错误提示应该是你用法不对，贴出代码看看。

**Comment by kency** [comment]
也有可能，降到7.1.15可以了，忘了当时代码怎么写的了
