### ISSUE TITLE
php  7.2.4 报错 /vendor/jaeger/phpquery-single/phpQuery.php] line[328] message:[DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 2070]

### ISSUE THREAD

**Issue by david0315** [jae-jae/QueryList#47]
![image](https://user-images.githubusercontent.com/3435608/46198024-07bcc300-c33e-11e8-861f-c48538f406e0.png)
代码如下
![image](https://user-images.githubusercontent.com/3435608/46198039-13a88500-c33e-11e8-9f6d-1b3d6d9277e8.png)

**Comment by duanjw** [comment]
调用``QueryList::Query() ``前设置``libxml_use_internal_errors(true);``试试。
