### ISSUE TITLE
改成laravel扩展了？

### ISSUE THREAD

**Issue by cncqw** [jae-jae/QueryList#50]
有时候只是想在php脚本里用一下，这样是没有灵魂的

**Comment by jae-jae** [comment]
QueryList是个独立的插件，与框架无关，可单独使用，也可以集成到任意框架中去使用。

**Comment by cncqw** [comment]
我就想在单文件脚本里使用一下，没有composer，请问怎么引入？

**Comment by edwinhuish** [comment]
说明文档里写了，可以用 QueryList3， 而且使用composer又不难。
