### ISSUE TITLE
有些页面无法采集/匹配到数据和内容

### ISSUE THREAD

**Issue by suhanyujie** [jae-jae/QueryList#54]
* 你好，群主，针对文档中的一些例子我在本地跑是ok的，可以匹配到内容，但是对于一些页面，采集不到，例如以下：

```php
$url = 'http://www.badmintoncn.com/';
$range = '.main .list-1 .list-1-top';
$rules = [
    'title' => ['a', 'text'],
];
$rt = QueryList::get($url)->rules($rules)
    ->range($range)->query()->getData();
var_dump($url,$rt->all());exit(PHP_EOL.'下午6:30'.PHP_EOL);	
```
* 获取到的数据为空，但实际上应该是有数据的

**Comment by suhanyujie** [comment]
看了一下，我匹配不出的应该是js渲染出来的

**Comment by suhanyujie** [comment]
* 我仔细看了一下，发现还是有些问题
* 当我匹配 `#slideshow` 下的 `ul li` 中的标签中的内容时，还是无法匹配出，因为这个它html中有的，不是js渲染出来的内容
* 我的代码如下：

```php
$url = 'http://www.badmintoncn.com/';
$range = '.left-box-1 list-2';
$rules = [
    'title' => ['a', 'text'],
];
$rt = QueryList::get($url)->rules($rules)
    ->range($range)->query()->getData();
var_dump($url,$rt->all());
```

* 执行的结果却是什么都没有：
>string(27) "http://www.badmintoncn.com/"
array(0) {
}

* 另：相比之下，我用nodejs的 cheerio 库 或者 go中的 goquery 库，使用类似的匹配规则都是可以正确匹配出内容的

**Comment by lirko** [comment]
$url = 'http://www.badmintoncn.com/';
$range = '';
$rules = [
    'title' => ['.left-box-1 .list-2 a', 'text'],
];
$rt = QueryList::get($url)->rules($rules)->range($range)->encoding('UTF-8')->removeHead()->query()->getData()->all();
var_dump($rt);
