### ISSUE TITLE
Fatal error: Call to undefined method Jaeger\GHttp::multiRequest()   这个方法没有实现？

### ISSUE THREAD

**Issue by woordee** [jae-jae/QueryList#66]
如题

`Exception trace:
 () at D:\wwwroot\127_0\public\vendor\jaeger\querylist\src\Services\MultiRequestService.php:36
 QL\Services\MultiRequestService->__construct() at D:\wwwroot\127_0\public\vendor\jaeger\querylist\src\Providers\HttpServiceProvider.php:33
 QL\QueryList->QL\Providers\{closure}() at n/a:n/a
 Closure->call() at D:\wwwroot\127_0\public\vendor\jaeger\querylist\src\QueryList.php:67`

**Comment by jae-jae** [comment]
composer update 试试

**Comment by woordee** [comment]
更新后可以了。谢谢
