### ISSUE TITLE
Parse error: syntax error, unexpected '='

### ISSUE THREAD

**Issue by bjfqy** [jae-jae/QueryList#72]
Parse error: syntax error, unexpected '='
![依赖包php7 0环境下 使用4 0 1版本出现bug](https://user-images.githubusercontent.com/40203543/56465991-94df7a80-643c-11e9-9f37-907cd56097b8.jpg)

**Comment by jae-jae** [comment]
Check if your PHP version is >= PHP7.0

**Comment by WeakChickenPeng** [comment]
[$a,$b] replace with list($a,$b)
