### ISSUE TITLE
列表采集数据不对

### ISSUE THREAD

**Issue by navysummer** [jae-jae/QueryList#73]
> $search_url = 'http://so.iqiyi.com/so/q_' . $keyword;
        $rules = [
            //div[@class='mod_search_result']/div/ul/li[1]/h3[@class="result_title"]
            'title' => ['div>h3','text'],
           //div[@class='mod_search_result']/div/ul/li[1]/a/img/@src
          'image' => ['a>img','src']
        ];
        $range = '.mod_search_result>div>ul';
        $data = QueryList::get($search_url)->rules($rules)->range($range)->query()->getData();
       //打印结果
       print_r($data->all());

**Comment by navysummer** [comment]
图片只采集了一个

**Comment by navysummer** [comment]
Array ( [0] => Array ( [title] => 倚天屠龙记  2003 倚天屠龙记  2019 倚天屠龙记之魔教教主  1993 倚天屠龙记之魔教教主（粤语）  1993 她在《倚天屠龙记》中跑龙套，却在这部剧中演女主，杨超越作配 倚天屠龙记 吴启华版 2001 倚天屠龙记：张翠山自刎，是俞岱岩逼的吗？谢逊一语道破 新倚天屠龙记：大婚，张无忌假装喝醉吻赵敏，赵敏这下可有罪受了 《倚天屠龙记》结局：周芷若双目失明，被张三丰带走感化 《倚天屠龙记》大结局！周芷若嫁给了这个男人，并为其生下一子 新倚天屠龙记剧情抢先看  2019 新倚天屠龙记：张无忌和赵敏吻出新高度，赶超苏有朋版，太甜了 《倚天屠龙记》大婚当晚，张无忌太猴急，吻得赵敏不知所措！ 《倚天屠龙记》各版本赵敏出场，谁惊艳到了你 倚天屠龙记 马景涛版  1994 倚天屠龙记 郑少秋版  1978 倚天屠龙记：张无忌放弃了皇位，成全了赵敏，却害死了他 倚天屠龙记  1978 倚天屠龙记：她高颜值和魔鬼身材，却没有一句台词，谁的错？ 神雕侠侣中杨过和小龙女是怎么死的，在倚天屠龙记中给出了答案 [image] => //pic3.iqiyipic.com/image/20190401/cc/85/a_50000181_m_601_m4_180_236.jpg ) )

**Comment by navysummer** [comment]
官方样式
Array
(
    [0] => Array
        (
            [title] => 快讯：iOS版QQ大面积闪退（网友反映已恢复）
            [link] => https://www.ithome.com/html/it/358734.htm
            [img] => //img.ithome.com/newsuploadfiles/thumbnail/2018/5/358734_240.jpg
            [desc] => iOS版QQ大面积闪退，原因未知。目前根据IT之家的网友反映，目前iOS版本的QQ已经恢复，但是近期的消息记录已经消失
        )

    [1] => Array
        (
            [title] => 阿里影业公布截至近15个月业绩：营收33亿元，增幅130%
            [link] => https://www.ithome.com/html/it/358728.htm
            [img] => //img.ithome.com/newsuploadfiles/thumbnail/2018/5/358728_240.jpg
            [desc] =>  阿里影业集团公布截至2018年3月31日的十五个月财务业绩：报告期内公司营业收入达到33.03亿元，较上一年同期十五个月的14.32亿元，增长幅度超130%
        )

    // ....
)

**Comment by navysummer** [comment]
用的是v4

**Comment by bostin** [comment]
@navysummer 请问怎么解决的？我也是这个问题呢
