### ISSUE TITLE
获取标题乱码

### ISSUE THREAD

**Issue by mydogger** [jae-jae/QueryList#74]
部分网页获取标题乱码，例如：

> $url = 'https://v.qq.com/x/cover/160hz7pnas07s15/n0027chsw7f.html?videoMark=';
$res = \QL\QueryList::get($url);
print_r($res->find('title')->text());

执行结果：

> $ php test.php
æå°±æ¯æ¼åããæ·±å¤é£å ãä¸ãæ¼æç¸è£ï¼åæ¬¢ä¸æ®µæ å£°è¡¨æ¼éæ¼å¨åºï¼è®©ç« å
­æ¡ç­æµæ³ª_ç»¼èº_é«æ¸1080På¨çº¿è§çå¹³å°_è¾è®¯è§é¢

如果查看完整的HTML代码，其实没有乱码。只由部分网页获取标题会乱码。

**Comment by sy-records** [comment]
使用`utf8_decode`函数处理一下就可以了。

```php
[root@sy-test querylist]# cat t.php 
<?php

require './vendor/autoload.php';

$url = 'https://v.qq.com/x/cover/160hz7pnas07s15/n0027chsw7f.html?videoMark=';
$res = \QL\QueryList::get($url);
$data =  $res->find('title')->text();
echo utf8_decode($data);

[root@sy-test querylist]# php t.php 
我就是演员【《深夜食堂》下】演技炸裂！刘欢一段无声表演震撼全场，让章子怡痛哭流泪_综艺_高清1080P在线观看平台_腾讯视频
```
