### ISSUE TITLE
手动安装的问题

### ISSUE THREAD

**Issue by CmderQ** [jae-jae/QueryList#8]
按照提供的文档，http://v3.querylist.cc/site/index/doc/7
手动进行安装，引入phpQuery.php和QueryList.php两个文件后，直接运行文档给的案例：
<?php
require 'phpQuery.php';
require 'QueryList.php';
use QL\QueryList;
$hj = QueryList::Query('http://mobile.csdn.net/',array("url"=>array('.unit h1 a','href')));
$data = $hj->getData(function($x){
    return $x['url'];
});
print_r($data);

结果显示：
Fatal error: Uncaught Error: Class 'QL\Dom\Query' not found in C:\www\NovelsReptile\QueryList.php:50 Stack trace: #0 C:\www\NovelsReptile\QueryList.php(83): QL\QueryList->__construct() #1 C:\www\NovelsReptile\QueryList.php(67): QL\QueryList::getInstance() #2 C:\www\NovelsReptile\spider.php(16): QL\QueryList::__callStatic('Query', Array) #3 {main} thrown in C:\www\NovelsReptile\QueryList.php on line 50
然后我尝试着把QueryList和phpQuery依赖的文件引入进来，然而并没有什么用！请问，这个手动安装的话，到底是怎么配？

**Comment by jae-jae** [comment]
你用的是QueryList4,V3下载地址：https://github.com/jae-jae/QueryList/tree/V3.2.1

**Comment by CmderQ** [comment]
恩恩，好的，感谢呢！已经看到了！问题解决了！
