### ISSUE TITLE
vender/tightenco/collect/src/Collect/Support/Arr.php 384行： [$value, $key] = static::explodePluckParameters($value, $key);

### ISSUE THREAD

**Issue by WeakChickenPeng** [jae-jae/QueryList#86]
my PHP version is 7.0.10.
The output error is as follows:
Warning: Class 'Tightenco\Collect\Support\Arr' not found 
parse error: syntax error, unexpected '=' in ****\vendor\tightenco\collect\src\Collect\Support\Arr.php on line 385
In my submission, [$value, $key]  replace with list($value,$key)

**Comment by jae-jae** [comment]
环境要求：PHP > 7.1
