### ISSUE TITLE
cURL error 56: Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by xtf-php** [jae-jae/QueryList#88]
$ql = QueryList::get('https://www.xiaohongshu.com/discovery/item/5da33f440000000001009d1c'
            ,[],[
                'verify'=>false,
                'proxy' => '58.218.200.253:8614',// 设置代理
                //设置超时时间，单位：秒
                'timeout' => 30,
            ]);

我本地开发环境使用可以查询  放到linux服务器上 会报这个错误（cURL error 56: Recv failure: Connection reset by peer） 找了好久没看到哪里的问题

**Comment by jae-jae** [comment]
代理使用例子：
```php
$ql = QueryList::get('http://httpbin.org/get',[
    'param1' => 'testvalue',
    'params2' => 'somevalue'
],[
    // 设置代理
    'proxy' => 'http://222.141.11.17:8118',
    //设置超时时间，单位：秒
    'timeout' => 30,
    'headers' => [
        'Referer' => 'https://querylist.cc/',
        'User-Agent' => 'testing/1.0',
        'Accept'     => 'application/json',
        'X-Foo'      => ['Bar', 'Baz'],
        'Cookie'    => 'abc=111;xxx=222'
    ]
]);
```
