### ISSUE TITLE
phpQuery.php方法中提示变量未定义的问题

### ISSUE THREAD

**Issue by CmderQ** [jae-jae/QueryList#9]
hi，jae-jae你好，我用composer安装最新版本的QueryList后，在PHPStorm中打开，查看PHPQuery.php文件时，在protected function charsetFromXML($markup)方法中(第479行)，提示变量$matches未定义；_phpToMarkupCallback($php, $charset = 'utf-8')方法中$m未定义；getDOMDocument($source)方法中，
self::$documents[$id]['document']的$id未定义等等。我想问下，这样写的原因是什么？为什么会出现这样的变量？

**Comment by jae-jae** [comment]
phpQuery官方已经不再维护，源代码里面存在很多历史遗留问题，现在只能靠大家共同去维护了，欢迎PR：[https://github.com/jae-jae/phpQuery-single](https://github.com/jae-jae/phpQuery-single)

**Comment by CmderQ** [comment]
好的，我研究下！感谢
