### ISSUE TITLE
phpQuery有个bug，那就是当HTML中有它无法识别的特殊字符时，HTML就会被截断，导致最终的采集结果不正确

### ISSUE THREAD

**Issue by ghost** [jae-jae/QueryList#90]
phpQuery有个bug，那就是当HTML中有它无法识别的特殊字符时，HTML就会被截断，导致最终的采集结果不正确，此时可以尝试使用正则或其它方式获取到要采集的内容的HTML片段，把这个HTML片段传给QueryList，从而可以解决这种场景下的问题。

请问这个BUG会修复吗?特殊字符,表情会中断,对我的业务需求来说.问题比较大.

**Comment by svipchao** [comment]
`/**
 * 对数据进行编码转换
 * @param array/string $data 数组
 * @param string $output 转换后的编码
 * Created on 2016-7-13
 */
function array_iconv($data,$output = 'utf-8') {
	$encode_arr = array('UTF-8','ASCII','GBK','GB2312','BIG5','JIS','eucjp-win','sjis-win','EUC-JP');
	$encoded = mb_detect_encoding($data,$encode_arr);
	if(!is_array($data)){
		return mb_convert_encoding($data,$output,$encoded);
	}else{
		foreach ($data as $key=>$val){
			$key = array_iconv($key, $output);
			if(is_array($val)) {
				$data[$key] = array_iconv($val, $output);
			}else{
				$data[$key] = mb_convert_encoding($data, $output, $encoded);
			}
		}
		return $data;
	}
}`

**Comment by svipchao** [comment]
`
/**
 * 对数据进行编码转换
 * @param array/string $data 数组
 * @param string $output 转换后的编码
 * Created on 2016-7-13
 */
function array_iconv($data,$output = 'utf-8') {
	$encode_arr = array('UTF-8','ASCII','GBK','GB2312','BIG5','JIS','eucjp-win','sjis-win','EUC-JP');
	$encoded = mb_detect_encoding($data,$encode_arr);
	if(!is_array($data)){
		return mb_convert_encoding($data,$output,$encoded);
	}else{
		foreach ($data as $key=>$val){
			$key = array_iconv($key, $output);
			if(is_array($val)) {
				$data[$key] = array_iconv($val, $output);
			}else{
				$data[$key] = mb_convert_encoding($data, $output, $encoded);
			}
		}
		return $data;
	}
}
`

**Comment by poetryiii** [comment]
[编码转换](https://gitee.com/shiwujintou/codes/y8nop0j9qa2lt3v5kbcfm29)

[解决采集HTML乱码](https://gitee.com/shiwujintou/codes/cq96zmwil7gyuvstjxhrk29)

**Comment by ghost** [comment]
转换后，用querylist采集过滤就有问题，就只能用正则了。这样意义不大。

**Comment by poetryiii** [comment]
没问题吧，我没遇见过

**Comment by jae-jae** [comment]
这个问题不太好修复，欢迎大家一起研究一下，给 phpQuery 项目提PR
