### ISSUE TITLE
采集https://news.baidu.com/guoji乱码

### ISSUE THREAD

**Issue by ken678** [jae-jae/QueryList#92]
![QQ截图20191108160952](https://user-images.githubusercontent.com/15792472/68460664-62b03180-0243-11ea-8f8f-6657d1d90372.jpg)

**Comment by jae-jae** [comment]
产生的乱码的原因有很多，还是得靠自己根据具体场景研究一下，解决乱码参考文档：http://querylist.cc/docs/guide/v4/content-processing
