### ISSUE TITLE
php 7.4 warning: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by x-controller** [jae-jae/QueryList#93]
{"exception":"[object] (ErrorException(code: 0): Array and string offset access syntax with curly braces is deprecated at /app/vendor/jaeger/phpquery-single/phpQuery.php:2170)

**Comment by AlexKitC** [comment]
把phpQuery文件的 2170行改成：if ($param[0] == 'n') 这样可以了

**Comment by cielu** [comment]
@jae-jae  麻烦解决下这个问题。。谢谢，不然每次都得手动改。。

**Comment by jae-jae** [comment]
已解决
